spring:
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/ssl?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=GMT%2B8
    username: root
    password: root
    hikari:
      minimum-idle: 3
      maximum-pool-size: 20
      #单位ms
      max-lifetime: 1200000
      connection-test-query: SELECT 1


### mybatis-plus
mybatis-plus:
  # 映射文件所在路径
  mapper-locations: classpath:mapper/*.xml
  # po类所在包路径
  type-aliases-package: com.example.docekr11041231.demos.model